
------------------------------------------------------------------
---------------------------- INSERTS -----------------------------
------------------------------------------------------------------

INSERT INTO public.appuser (uskey, uslogin, uspassword, usemail, usfirstname, uslastname, usdob, uscreatedon, uslastlogin) VALUES (1, 'admin', '$2b$10$FwpX/8N3Z9Aqhr0RhDeEb.i56mnJ5bCL8CfxTKHpY96bPSNneW8.K', 'g@g.com', 'admin', 'admin', '2018-12-24', '2018-12-24', '2018-12-24 19:47:43.188062+01');
INSERT INTO public.appuser (uskey, uslogin, uspassword, usemail, usfirstname, uslastname, usdob, uscreatedon, uslastlogin) VALUES (10, 'kt', '$2b$10$FwpX/8N3Z9Aqhr0RhDeEb.i56mnJ5bCL8CfxTKHpY96bPSNneW8.K', 'g@g.com', 'k', 't', NULL, '2018-12-24', '2018-12-24 19:47:43.188062+01');

INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (3, 'Chest', NULL);
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (4, 'Shoulders', NULL);
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (5, 'Arms', NULL);
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (6, 'ABS', 'The abdominal muscles.');
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (7, 'Glutes', NULL);
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (1, 'Legs', 'The human leg, in the general meaning, is the entire lower limb of the human body, including the foot, thigh and even the hip or gluteal region. However, the definition in human anatomy refers only to the section of the lower limb extending from the knee to the ankle, also known as the crus.[3][4][5] Legs are used for standing, and all forms of locomotion including recreational such as dancing, and constitute a significant portion of a person''s mass. Female legs generally have greater hip anteversion and tibiofemoral angles, but shorter femur and tibial lengths than those in males.');
INSERT INTO public.bodyparts (bpkey, bpname, bpdescription) VALUES (2, 'Back', 'The human back is the large posterior area of the human body, rising from the top of the buttocks to the back of the neck and the shoulders. It is the surface of the body opposite from the chest. The vertebral column runs the length of the back and creates a central area of recession. The breadth of the back is created by the shoulders at the top and the pelvis at the bottom.');

INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (6, 'Pull-up', 'A pull-up is an upper-body compound pulling exercise. Although it can be performed with any grip, in recent years some have used the term to refer more specifically to a pull-up performed with a palms-forward position', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (1, 'Squat', 'In strength training and fitness, the squat is a compound, full body exercise that trains primarily the muscles of the thighs, hips and buttocks, quadriceps femoris muscle (vastus lateralis, vastus medialis, vastus intermedius and rectus femoris), hamstrings, as well as strengthening the bones, ligaments and insertion of the tendons throughout the lower body. Squats are considered a vital exercise for increasing the strength and size of the legs as well as developing core strength. Squats are typically used to hone back, thigh, and hip stability.[1] Isometrically, the lower back, the upper back, the abdominals, the trunk muscles, the costal muscles, and the shoulders and arms are all essential to the exercise and thus are trained when squatting with the proper form.', '', 1, 10, '2019-01-01 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (4, 'Deadlift', 'The deadlift is a weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, then lowered to the ground.[1] It is one of the three powerlifting exercises, along with the squat and bench press.', '', 1, 10, '2019-01-01 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (5, 'Bench press', 'A man performs a barbell bench press while another spots him.
The bench press is an upper body strength training exercise that consists of pressing a weight upwards from a supine position. The exercise works the pectoralis major as well as supporting chest, arm, and shoulder muscles such as the anterior deltoids, serratus anterior, coracobrachialis, scapulae fixers, trapezii, and the triceps. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.

The barbell bench press is one of three lifts in the sport of powerlifting (alongside the deadlift and squat) and is the only lift in the sport of Paralympic powerlifting.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (8, 'Overhead press', 'The press, overhead press or shoulder press is a weight training exercise with many variations, typically performed while standing, in which a weight is pressed straight upwards from racking position until the arms are locked out overhead, while the legs, lower back and abs maintain balance.[1] The exercise helps build muscular shoulders with bigger arms, and is one of the most difficult compound upper-body exercises.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (9, 'Biceps curl', 'Although the exercises differ, a common factor of each is a ''curling'' motion, where a weight (attached to, or used in conjunction with, an item of equipment listed above) is lifted up until the forearms are vertical[1] with the elbows and upper arm remaining close to the body.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (10, 'Dip', 'The dip or push-ups is an exercise used in strength training. Narrow, shoulder-width dips primarily train the triceps, with major synergists being the anterior deltoid, the pectoralis muscles (sternal, clavicular, and minor), and the rhomboid muscles of the back (in that order).[1] Wide arm training places additional emphasis on the pectoral muscles, similar in respect to the way a wide grip bench press would focus more on the pectorals and less on the triceps.[2] Proper form is important to avoid putting undue stress on the wrists.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (11, 'Push-up', 'A push-up (or press-up) is a common calisthenics exercise beginning from the prone position, or the front leaning rest position known in the military. By raising and lowering the body using the arms, push-ups exercise the pectoral muscles, triceps, and anterior deltoids, with ancillary benefits to the rest of the deltoids, serratus anterior, coracobrachialis and the midsection as a whole. Push-ups are a basic exercise used in civilian athletic training or physical education and commonly in military physical training. They are also a common form of punishment used in the military, school sport, or in some martial arts disciplines.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (12, 'Front Squat', 'Front squats are a variation of the barbell squat where the weight is placed on the front shoulders instead of the back. Because of the change in position, front squats place additional emphasis on the upper body (i.e. traps, lats and shoulders) when compared to barbell squats and thus most athletes use lighter weights.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (13, 'Hip Thrust', 'The Hip Thrust is a glute exercise designed to improve your strength, speed and power by teaching optimal hip extension. What is "optimal hip extension," and why should you care about it? It''s all about the power in your glutes, which are among the most powerful muscles in your body. The glutes are designed to extend the hip or pull the leg behind the body. If your glutes are underdeveloped, your speed, power and strength are all compromised. That means you''ll have weaker Squats and Deadlifts as well as slower 40-Yard Dash times and lower vertical jumps than you could have otherwise.', NULL, 1, 10, '2019-01-27 00:00:00+01');
INSERT INTO public.exercise (exkey, exname, exdescription, exiconname, exsetsunit, excreatedby, excreatedon) VALUES (7, 'Plank', 'The plank (also called a front hold, hover, or abdominal bridge) is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.', NULL, 2, 10, '2019-01-27 00:00:00+01');

INSERT INTO public.txt (txt, createdon) VALUES ('2/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.910', '2019-03-06 21:28:21.997758+01');
INSERT INTO public.txt (txt, createdon) VALUES ('2/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.910', '2019-03-06 21:28:29.584931+01');
INSERT INTO public.txt (txt, createdon) VALUES ('2/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.910', '2019-03-06 21:30:03.0448+01');
INSERT INTO public.txt (txt, createdon) VALUES ('2/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.9102/6/2019 21:22:52.910', '2019-03-06 21:30:16.697644+01');
commit;